# Generated by Django 3.2.8 on 2021-11-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stack',
            field=models.CharField(choices=[('backend', 'BACKEND'), ('frontend', 'FRONTEND'), ('seo', 'SEO'), ('ui_ux', 'UI|UX DESIGNER')], max_length=64),
        ),
    ]
