# Generated by Django 3.2.8 on 2021-11-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('started', 'STARTED'), ('late_submitted', 'LATE SUBMITTED'), ('completed', 'COMPLETED')], max_length=64),
        ),
    ]
