# Generated by Django 3.2.8 on 2021-11-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20211105_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
