# Generated by Django 3.2.8 on 2021-11-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_task_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(blank=True, choices=[('critical', 'CRITICAL'), ('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
