# Generated by Django 3.2.8 on 2021-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20211106_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.CharField(blank=True, choices=[('completed', 'COMPLETED'), ('not_completed', 'NOT COMPLETED')], max_length=64, null=True),
        ),
    ]
