# Generated by Django 3.2.8 on 2021-11-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.task'),
        ),
    ]
