# Generated by Django 3.2.8 on 2021-11-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_problem_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default='2020-12-30'),
        ),
    ]
