# Generated by Django 3.2.8 on 2021-11-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20211108_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('not_completed', 'NOT COMPLETED')], default='completed', max_length=64),
        ),
    ]
