# Generated by Django 3.2.8 on 2021-11-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_problem_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='completed',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('not_completed', 'NOT COMPLETED')], default='not_completed', max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('not_completed', 'NOT COMPLETED')], default='not_completed', max_length=64),
        ),
    ]
