# Generated by Django 3.2.8 on 2021-11-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20211112_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
