# Generated by Django 3.2.8 on 2021-11-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20211112_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=125, null=True)),
                ('priority', models.CharField(blank=True, choices=[('critical', 'CRITICAL'), ('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], max_length=64, null=True)),
                ('status', models.CharField(choices=[('fixed_bug', 'FIXED BUG'), ('not_fixed_bug', 'NOT FIXED BUG')], default='not_fixed_bug', max_length=64)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
        ),
    ]
