# Generated by Django 3.2.8 on 2021-11-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
